### ISSUE TITLE
bugs in the preview image and after the installation of the style

### ISSUE THREAD

**Issue by JAKill02** [userstyles-world/userstyles.world#67] opened 2021-07-15 02:55 UTC
Hello everyone.

First of all, I want to note that when installing from this resource, sections with global rules are ignored and become inactive (and disappear from the tree of sections).
 
further, after installation in the style, you cannot create new sections, move them Below/Above, and when working in the current section, Stylus does not highlight the name of the active section in the left column (tree of sections).
there are also no Import and Export buttons.

all this appears or starts working if you select the entire installed style, copy it to the clipboard, create an empty new style and paste the copied one, but none of the above works when installed from the site itself.

and the Preview image on the style page looks like an incomprehensible mess.
![xxx_](https://user-images.githubusercontent.com/55640282/125720710-fe0dc0e9-5786-4826-8caf-cb43f2cd1567.png)
![img_](https://user-images.githubusercontent.com/55640282/125720998-34c27f35-391c-430f-a400-4fafbb0a5d3f.png)

**Comment by Gusted** [comment] 2021-07-15 08:28
> First of all, I want to note that when installing from this resource, sections with global rules are ignored and become inactive (and disappear from the tree of sections).

Open up a issue in [stylus](https://github.com/openstyles/stylus) that is non-related to us.



> further, after installation in the style, you cannot create new sections, move them Below/Above, and when working in the current section, Stylus does not highlight the name of the active section in the left column (tree of sections).
> there are also no Import and Export buttons.

Once again, this is not us, this is [stylus](https://github.com/openstyles/stylus).

> all this appears or starts working if you select the entire installed style, copy it to the clipboard, create an empty new style and paste the copied one, but none of the above works when installed from the site itself.

Still not sure how it relates, so [stylus](https://github.com/openstyles/stylus).



> and the Preview image on the style page looks like an incomprehensible mess.

Give the server some time to convert the image into other formats and give it after ~1 minute a refresh.

**Comment by JAKill02** [comment] 2021-07-15 09:11
i figured out what the problem is, these are the limitations and flaws in the style format in UserCSS.

sadly, in such conditions it is easier to provide people with a .txt document and write instructions on how to manually install a style from it into Stylus. at least the possibilities will not be limited and everything will work as intended.

/ * == UserStyle ==
== / UserStyle == * / has existed for a long time, and since no one has bothered with these problems during this time, it means that no one will deal with this.

**Comment by JAKill02** [comment] 2021-07-15 09:38
will it be possible to use the classic version of writing a style on userstyles.world, instead of installing via UserCSS, as could it be done on userstyles.org ?
(the opportunity for the author to choose how to write the style and the ability of the site to understand the differences in writing the style)

**Comment by vednoc** [comment] 2021-07-15 10:05
> sections with global rules are ignored and become inactive (and disappear from the tree of sections)

I noticed they do show up after you click a couple of times to hide/show the sections. It seems like a bug in Stylus in `v1.5.18` because it doesn't have that issue in `v1.5.17`. Not highlighting the active section does seem like a bug as well.


> you cannot create new sections, move them Below/Above

That's because everything is plain text: sections are just `@-moz-document` blocks and to move them around, you can just cut and paste them. Implementation of UserCSS and traditional format are quite different, and so are the features/inconsistencies between them.


> at least the possibilities will not be limited and everything will work as intended

As a user, it doesn't matter to me as long as the minimal work on my end is necessary. Your userstyle doesn't install because its version doesn't follow [SemVer](https://semver.org/) scheme. I had to install it manually like so:
```diff
-@version        v1.5.8+28
+@version        1.5.828
```


> the Preview image on the style page looks like an incomprehensible mess

Does it not look like the image below? If so, we'll need to know which browser you're using in order to reproduce the issue.

![image](https://user-images.githubusercontent.com/18245694/125765010-32f6b922-e4b0-4630-af9c-6f684301ad50.png)


> will it be possible to use the classic version of writing a style on userstyles.world

Maybe, if there's a significant amount of users that find the lack of this functionality a deal-breaking feature. The implementation side of things would be, to put it simply, extremely tedious. We would have to implement that wheel from the scratch only for you to not be able to install it because traditional userstyles require that the extension communicates to the server and whatnot. That doesn't even include custom settings, the complexity of which increases tenfold if we choose to support them.

**Comment by JAKill02** [comment] 2021-07-15 10:31
:D Such strange numbering of versions went due to the restrictions on userstyles.org of 250 kilobytes on the size of the style, I already had nowhere to develop further and all that remained was to change the style a little due to the changes introduced by YouTube within this size.

(v1.5.8) version number. (+ 28) the number of the change made to this version.

I use "Cent Browser"
Version 4.3.9.248 (Official assembly), (32 bit) (Portable) (Chromium 86.0.4240.198)

**Comment by vednoc** [comment] 2021-07-15 10:55
The version is still bad. The `+28` should be completely removed because you already put it in the title. Try to install it now and you'll get an error.

As for Cent Browser, it's not that old and what we use there has been supported even on Firefox v56 from 4 years ago. Try to force-refresh the page (press `CTRL` + `F5`) to invalidate the cache.

**Comment by JAKill02** [comment] 2021-07-15 11:13
I opened a new window in incognito mode, having previously disabled all extensions that I had running and which was given permission to work in incognito.
aaaand, nothing has changed ¯ \ _ (ツ) _ / ¯
![Incognito](https://user-images.githubusercontent.com/55640282/125779012-ca5a7250-f351-4b98-b302-437ecaa2b74e.PNG)

**Comment by vednoc** [comment] 2021-07-15 11:34
Looks like I'll need to set up a virtual machine in order to test this bug.

**Comment by JAKill02** [comment] 2021-07-15 11:48
if you try to go to the address of the preview picture for the style, specified in the editing mode, the picture is not available. 
( {"error":"bad endpoint"}  )
could this be the problem?
![pic](https://user-images.githubusercontent.com/55640282/125783169-97f07bcd-73c4-43c8-ba6d-7a1a49681595.PNG)

**Comment by vednoc** [comment] 2021-07-15 12:11
Oh no. You can fix it now by changing to `https://userstyles.world/api/style/preview/285.jpeg` or by waiting for me to update it manually, which is what I'm going to do now for all styles that are affected.

**Comment by JAKill02** [comment] 2021-07-15 13:00
it somehow doesn't want to. XD after changing the link manually, the screenshot disappears completely.

**Comment by vednoc** [comment] 2021-07-15 13:16
I just updated your style in the database. Do another force-refresh, it really _shouldn't_ disappear or anything like that.

**Comment by JAKill02** [comment] 2021-07-15 13:24
the image is there, even though it's still a blurry mess, but I'm already glad that there is at least something, it's better than nothing. )

**Comment by vednoc** [comment] 2021-07-15 13:41
Try it with another browser if you can. It should look exactly like what I posted in my first reply. The blurred image is there as a backdrop, and the image that's on top of it will use original aspect ratio and size, yet it's missing on your end for some reason.

**Comment by JAKill02** [comment] 2021-07-15 14:06
hmm, it looks like this is a personal bug of the Cent Browser's, on the older version of the Cent it's still the same, but on the ancient Firefox 52, well... it's better than on the Cent.
with a picture, we can consider that the question is closed.

![FF 52](https://user-images.githubusercontent.com/55640282/125801447-fc200b88-35ea-4fd4-9f7f-91b84a52b8f3.PNG)

**Comment by vednoc** [comment] 2021-07-15 14:36
Seems like Cent Browser doesn't support `display: grid` which is what we're using to center the image within that container. Also, it seems like Firefox v52 doesn't support WebP images, which is why you're missing a blurry background there.

I planned to rewrite the UI and use CSS Grid everywhere. This issue makes it so that we need to add fallback for old browsers that don't support CSS Grid.

**Comment by vednoc** [comment] 2021-07-15 15:50
I just updated the server with fixes for aforementioned bugs. Let us know what it looks like now.

**Comment by JAKill02** [comment] 2021-07-15 16:17
my respect, it looks great now.

![!](https://user-images.githubusercontent.com/55640282/125822093-699fde09-b173-45b2-a723-f1952872275e.PNG)

**Comment by vednoc** [comment] 2021-07-15 16:23
Awesome! My guesses were exactly on point. 🎉

**Comment by Gusted** [comment] 2021-07-16 20:01
In that case, bug fixed and resolved by our Judge @vednoc

**Closed by Gusted** 2021-07-16 20:01 UTC
Labels: bug
